"""Visualization output generators for DepPulse dependency graphs.

Supports three output formats:
- Mermaid flowchart code
- Graphviz DOT format
- Interactive HTML dashboard with D3.js
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

import networkx as nx

from deppulse.models import GraphBuildResult, Language


# ---------------------------------------------------------------------------
# Mermaid
# ---------------------------------------------------------------------------


def render_mermaid_graph(
    graph: nx.DiGraph,
    *,
    title: str = "Dependency Graph",
    max_nodes: int = 200,
) -> str:
    """
    Render a dependency graph as a Mermaid flowchart.

    Groups nodes by language into subgraphs, colors edges by dependency kind,
    and marks high-risk nodes (high in-degree) with a warning style.
    """
    lines = [f"flowchart LR", f'    %% {title} — generated by DepPulse']

    # Color scheme by language
    lang_colors = {
        Language.PYTHON: "#4B8BBE",
        Language.JAVA: "#B07219",
        Language.KOTLIN: "#A18B00",
        Language.CPP: "#F34B7D",
        Language.UNKNOWN: "#AAAAAA",
    }

    # Group nodes by language
    lang_groups: dict[str, list[str]] = {}
    node_lang: dict[str, Language] = {}
    node_risk: dict[str, bool] = {}

    for node in graph.nodes():
        data = graph.nodes[node] if node in graph.nodes else {}
        lang = data.get("language", Language.UNKNOWN)
        in_deg = graph.in_degree(node)
        high_risk = in_deg > 5  # heuristic: high fan-in = high risk

        node_lang[node] = lang
        node_risk[node] = high_risk

        suffix = data.get("suffix", Path(node).suffix)
        if suffix == ".py":
            lang_key = "Python"
        elif suffix == ".java":
            lang_key = "Java"
        elif suffix in (".kt", ".kts"):
            lang_key = "Kotlin"
        elif suffix in (".c", ".cpp", ".h", ".hpp", ".cc"):
            lang_key = "C/C++"
        else:
            lang_key = "Other"

        lang_groups.setdefault(lang_key, []).append(node)

    # Define subgraph IDs
    subgraph_ids: dict[str, str] = {}
    for i, key in enumerate(sorted(lang_groups.keys())):
        subgraph_ids[key] = f"sg{i}"

    # Declare subgraph styles
    color_map = {
        "Python": "#4B8BBE",
        "Java": "#B07219",
        "Kotlin": "#A18B00",
        "C/C++": "#F34B7D",
        "Other": "#AAAAAA",
    }

    shown = 0
    for lang_key, nodes in sorted(lang_groups.items()):
        sg_id = subgraph_ids[lang_key]
        color = color_map.get(lang_key, "#AAAAAA")
        lines.append(f'    subgraph {sg_id} ["{lang_key}"]')
        for node in nodes[:max_nodes]:
            if shown >= max_nodes:
                break
            node_id = _safe_node_id(node)
            node_color = "#e74c3c" if node_risk.get(node, False) else f"#{color}"
            label = _escape_mermaid(Path(node).name)
            style = "fill:#e74c3c,stroke:#c0392b,stroke-width:2px" if node_risk.get(node) else f"fill:#{color},color:#fff"
            lines.append(f'        {node_id}["{label}"]')
            shown += 1
        lines.append("    end")

    # Add edge styles
    kind_colors = {
        "import": "#27ae60",
        "java_import": "#d35400",
        "kotlin_import": "#8e44ad",
        "include_local": "#2980b9",
        "include_system": "#7f8c8d",
    }

    # Draw edges
    for u, v, data in graph.edges(data=True):
        u_id = _safe_node_id(u)
        v_id = _safe_node_id(v)
        kind = data.get("kind", "unknown")
        color = kind_colors.get(kind, "#95a5a6")
        lines.append(f"    {u_id} -.->|\"{kind}\"| {v_id}")

    if shown == 0:
        lines.append('    empty["(no nodes)"]')

    return "\n".join(lines)


def graph_to_mermaid(
    graph: nx.DiGraph,
    *,
    title: str = "Dependency Graph",
) -> str:
    """Alias for render_mermaid_graph for compatibility."""
    return render_mermaid_graph(graph, title=title)


# ---------------------------------------------------------------------------
# Graphviz DOT
# ---------------------------------------------------------------------------


def render_dot_graph(
    graph: nx.DiGraph,
    *,
    title: str = "Dependency Graph",
) -> str:
    """
    Render a dependency graph as Graphviz DOT format.

    Nodes are colored by language, sized by in-degree, and high-risk
    nodes (many dependents) are highlighted in red.
    """
    lines = [
        "digraph dependencies {",
        f'    label="{_escape_dot(title)}";',
        '    labelloc="t";',
        '    rankdir=LR;',
        '    node [shape=box, style="rounded,filled", fontname=Helvetica, width=0.3];',
        '    edge [arrowsize=0.5];',
    ]

    lang_colors = {
        Language.PYTHON: "#4B8BBE",
        Language.JAVA: "#B07219",
        Language.KOTLIN: "#A18B00",
        Language.CPP: "#F34B7D",
        Language.UNKNOWN: "#AAAAAA",
    }

    default_color = "#AAAAAA"

    for node in graph.nodes():
        data = graph.nodes[node] if node in graph.nodes else {}
        suffix = data.get("suffix", Path(node).suffix)
        in_deg = graph.in_degree(node)
        high_risk = in_deg > 5

        if suffix == ".py":
            color = "#4B8BBE"
        elif suffix == ".java":
            color = "#B07219"
        elif suffix in (".kt", ".kts"):
            color = "#A18B00"
        elif suffix in (".c", ".cpp", ".h", ".hpp", ".cc"):
            color = "#F34B7D"
        else:
            color = default_color

        if high_risk:
            color = "#e74c3c"

        label = _escape_dot(Path(node).name)
        lines.append(f'    "{_escape_dot(node)}" [label="{label}", fillcolor="{color}", color="#fff"];')

    for u, v, data in graph.edges(data=True):
        kind = data.get("kind", "unknown")
        lines.append(f'    "{_escape_dot(u)}" -> "{_escape_dot(v)}" [label="{kind}", color="#95a5a6", fontsize=8];')

    lines.append("}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML Dashboard
# ---------------------------------------------------------------------------


def render_html_dashboard(
    result: GraphBuildResult,
    graph: nx.DiGraph,
    *,
    output_path: Path = Path("deppulse-dashboard.html"),
) -> None:
    """
    Generate a standalone interactive HTML dependency dashboard.

    Uses D3.js force-directed graph for visualization. All JS/CSS is embedded.
    """
    # Gather node data
    nodes_data: list[dict] = []
    edges_data: list[dict] = []
    lang_map = {
        ".py": "python",
        ".java": "java",
        ".kt": "kotlin",
        ".kts": "kotlin",
        ".c": "cpp",
        ".cpp": "cpp",
        ".h": "cpp",
        ".hpp": "cpp",
        ".cc": "cpp",
        ".cxx": "cpp",
    }

    lang_colors = {
        "python": "#4B8BBE",
        "java": "#B07219",
        "kotlin": "#A18B00",
        "cpp": "#F34B7D",
    }

    node_ids: dict[str, int] = {}

    # Add phantom edges for unresolved dependencies
    for scan_result in result.scan_results:
        for resolved in scan_result.unresolved_dependencies:
            # Just track unresolved counts
            pass

    for i, node in enumerate(graph.nodes()):
        data = graph.nodes[node] if node in graph.nodes else {}
        suffix = data.get("suffix", Path(node).suffix)
        lang = lang_map.get(suffix, "unknown")
        in_deg = graph.in_degree(node)
        out_deg = graph.out_degree(node)

        node_ids[node] = i
        nodes_data.append({
            "id": node,
            "name": Path(node).name,
            "lang": lang,
            "lang_color": lang_colors.get(lang, "#AAAAAA"),
            "group": lang,
            "size": max(4, min(20, in_deg + 3)),  # size by fan-in
            "in_deg": in_deg,
            "out_deg": out_deg,
        })

    for u, v, data in graph.edges(data=True):
        if u in node_ids and v in node_ids:
            edges_data.append({
                "source": u,
                "target": v,
                "kind": data.get("kind", "unknown"),
                "line_number": data.get("line_number", 0),
            })

    import json

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>DepPulse — Dependency Dashboard</title>
<script src="https://d3js.org/d3.v7.min.js"></script>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: #0f1419;
    color: #e6edf3;
    overflow: hidden;
  }}
  #header {{
    position: fixed; top: 0; left: 0; right: 0;
    height: 48px;
    background: rgba(15,20,25,0.95);
    border-bottom: 1px solid #30363d;
    display: flex; align-items: center; padding: 0 16px;
    gap: 24px;
    z-index: 100;
  }}
  #header h1 {{
    font-size: 16px; font-weight: 600; color: #58a6ff;
  }}
  #stats {{
    font-size: 12px; color: #8b949e;
    display: flex; gap: 16px;
  }}
  #stats span {{ display: flex; align-items: center; gap: 4px; }}
  #stats .val {{ color: #e6edf3; font-weight: 500; }}
  #graph-container {{
    position: fixed; top: 48px; left: 0; right: 0; bottom: 0;
  }}
  svg {{
    width: 100%; height: 100%; display: block;
  }}
  .node circle {{
    stroke: rgba(255,255,255,0.2);
    stroke-width: 1.5px;
    cursor: pointer;
    transition: r 0.2s;
  }}
  .node circle:hover {{
    stroke: #fff;
    stroke-width: 2px;
  }}
  .node text {{
    font-size: 9px;
    fill: #e6edf3;
    text-anchor: middle;
    pointer-events: none;
    dominant-baseline: middle;
  }}
  .link {{
    stroke: #30363d;
    stroke-opacity: 0.5;
    stroke-width: 1px;
  }}
  .link:hover {{
    stroke: #58a6ff;
    stroke-opacity: 1;
  }}
  #tooltip {{
    position: fixed;
    background: rgba(22,27,34,0.97);
    border: 1px solid #30363d;
    border-radius: 6px;
    padding: 8px 12px;
    font-size: 12px;
    pointer-events: none;
    display: none;
    z-index: 200;
    max-width: 280px;
  }}
  #tooltip .path {{ color: #58a6ff; word-break: break-all; font-family: monospace; font-size: 11px; }}
  #tooltip .meta {{ margin-top: 4px; color: #8b949e; }}
  #tooltip .lang {{ display: inline-block; padding: 1px 6px; border-radius: 3px; font-size: 10px; }}
  #legend {{
    position: fixed; bottom: 16px; right: 16px;
    background: rgba(22,27,34,0.9);
    border: 1px solid #30363d;
    border-radius: 6px;
    padding: 10px 14px;
    font-size: 11px;
    z-index: 100;
  }}
  #legend .title {{ color: #8b949e; margin-bottom: 6px; font-weight: 500; }}
  #legend .item {{ display: flex; align-items: center; gap: 6px; margin: 3px 0; }}
  #legend .dot {{
    width: 10px; height: 10px; border-radius: 50%;
    flex-shrink: 0;
  }}
  #controls {{
    position: fixed; top: 56px; left: 16px;
    background: rgba(22,27,34,0.9);
    border: 1px solid #30363d;
    border-radius: 6px;
    padding: 10px 14px;
    font-size: 11px;
    z-index: 100;
    display: flex; flex-direction: column; gap: 8px;
    min-width: 160px;
  }}
  #controls .title {{ color: #8b949e; font-weight: 500; margin-bottom: 2px; }}
  #controls button {{
    background: #21262d; color: #c9d1d9; border: 1px solid #30363d;
    border-radius: 4px; padding: 4px 8px; font-size: 11px; cursor: pointer;
    transition: background 0.15s;
  }}
  #controls button:hover {{ background: #30363d; }}
  #info-panel {{
    position: fixed; top: 56px; right: 16px;
    width: 260px;
    background: rgba(22,27,34,0.95);
    border: 1px solid #30363d;
    border-radius: 6px;
    padding: 12px;
    font-size: 12px;
    z-index: 100;
    display: none;
  }}
  #info-panel h3 {{ color: #58a6ff; font-size: 13px; margin-bottom: 8px; }}
  #info-panel .row {{ display: flex; justify-content: space-between; margin: 4px 0; color: #8b949e; }}
  #info-panel .row .v {{ color: #e6edf3; }}
</style>
</head>
<body>
<div id="header">
  <h1>DepPulse</h1>
  <div id="stats">
    <span><span class="val" id="stat-nodes">0</span> files</span>
    <span><span class="val" id="stat-edges">0</span> deps</span>
    <span><span class="val" id="stat-python">0</span> Python</span>
    <span><span class="val" id="stat-java">0</span> Java</span>
    <span><span class="val" id="stat-kotlin">0</span> Kotlin</span>
  </div>
</div>

<div id="controls">
  <div class="title">Controls</div>
  <button id="btn-zoom-in">Zoom In</button>
  <button id="btn-zoom-out">Zoom Out</button>
  <button id="btn-reset">Reset View</button>
</div>

<div id="graph-container"></div>

<div id="tooltip">
  <div class="path"></div>
  <div class="meta">
    <span class="lang"></span>
    <span class="deg"></span>
  </div>
</div>

<div id="legend">
  <div class="title">Language</div>
  <div class="item"><div class="dot" style="background:#4B8BBE"></div> Python</div>
  <div class="item"><div class="dot" style="background:#B07219"></div> Java</div>
  <div class="item"><div class="dot" style="background:#A18B00"></div> Kotlin</div>
  <div class="item"><div class="dot" style="background:#F34B7D"></div> C/C++</div>
  <div class="item"><div class="dot" style="background:#AAAAAA"></div> Other</div>
</div>

<script>
const DATA = {{
  nodes: {json.dumps(nodes_data, ensure_ascii=False)},
  edges: {json.dumps(edges_data, ensure_ascii=False)}
}};

// Update stats
document.getElementById('stat-nodes').textContent = DATA.nodes.length;
document.getElementById('stat-edges').textContent = DATA.edges.length;
const langCounts = {{}};
DATA.nodes.forEach(n => {{ langCounts[n.lang] = (langCounts[n.lang] || 0) + 1; }});
if (langCounts.python) document.getElementById('stat-python').textContent = langCounts.python;
if (langCounts.java) document.getElementById('stat-java').textContent = langCounts.java;
if (langCounts.kotlin) document.getElementById('stat-kotlin').textContent = langCounts.kotlin;

// Build id->index map
const idMap = {{}};
DATA.nodes.forEach((n, i) => {{ idMap[n.id] = i; }});

// D3 force-directed graph
const container = document.getElementById('graph-container');
const width = container.clientWidth;
const height = container.clientHeight;

const svg = d3.select('#graph-container')
  .append('svg')
  .attr('width', width)
  .attr('height', height);

const g = svg.append('g');

const zoom = d3.zoom()
  .scaleExtent([0.05, 4])
  .on('zoom', (event) => {{ g.attr('transform', event.transform); }});

svg.call(zoom);

const simulation = d3.forceSimulation(DATA.nodes)
  .force('link', d3.forceLink(DATA.edges)
    .id(d => d.id)
    .distance(60)
    .strength(0.3))
  .force('charge', d3.forceManyBody().strength(-120))
  .force('center', d3.forceCenter(width / 2, height / 2))
  .force('collision', d3.forceCollide().radius(d => d.size + 4));

const link = g.append('g')
  .selectAll('.link')
  .data(DATA.edges)
  .join('line')
  .attr('class', 'link')
  .attr('title', d => `${{d.source.id || d.source}} → ${{d.target.id || d.target}} (${{d.kind}})`);

const node = g.append('g')
  .selectAll('.node')
  .data(DATA.nodes)
  .join('g')
  .attr('class', 'node')
  .call(d3.drag()
    .on('start', (event, d) => {{
      if (!event.active) simulation.alphaTarget(0.3).restart();
      d.fx = d.x; d.fy = d.y;
    }})
    .on('drag', (event, d) => {{
      d.fx = event.x; d.fy = event.y;
    }})
    .on('end', (event, d) => {{
      if (!event.active) simulation.alphaTarget(0);
      d.fx = null; d.fy = null;
    }}));

node.append('circle')
  .attr('r', d => d.size)
  .attr('fill', d => d.lang_color)
  .attr('stroke', d => d.in_deg > 5 ? '#e74c3c' : 'rgba(255,255,255,0.15)');

node.append('text')
  .text(d => d.name.length > 14 ? d.name.slice(0, 12) + '..' : d.name)
  .attr('dy', d => d.size + 10);

const tooltip = document.getElementById('tooltip');

node.on('mouseover', (event, d) => {{
  tooltip.style.display = 'block';
  tooltip.style.left = (event.clientX + 12) + 'px';
  tooltip.style.top = (event.clientY + 12) + 'px';
  tooltip.querySelector('.path').textContent = d.id;
  tooltip.querySelector('.lang').textContent = d.lang;
  tooltip.querySelector('.lang').style.background = d.lang_color;
  tooltip.querySelector('.deg').textContent = `in:${{d.in_deg}} out:${{d.out_deg}}`;
}});

node.on('mousemove', (event) => {{
  tooltip.style.left = (event.clientX + 12) + 'px';
  tooltip.style.top = (event.clientY + 12) + 'px';
}});

node.on('mouseout', () => {{
  tooltip.style.display = 'none';
}});

simulation.on('tick', () => {{
  link
    .attr('x1', d => d.source.x)
    .attr('y1', d => d.source.y)
    .attr('x2', d => d.target.x)
    .attr('y2', d => d.target.y);
  node.attr('transform', d => `translate(${{d.x}},${{d.y}})`);
}});

// Controls
document.getElementById('btn-zoom-in').onclick = () => svg.transition().call(zoom.scaleBy, 1.3);
document.getElementById('btn-zoom-out').onclick = () => svg.transition().call(zoom.scaleBy, 0.7);
document.getElementById('btn-reset').onclick = () => svg.transition().call(zoom.transform, d3.zoomIdentity);

// Resize handler
window.addEventListener('resize', () => {{
  const w = container.clientWidth;
  const h = container.clientHeight;
  svg.attr('width', w).attr('height', h);
  simulation.force('center', d3.forceCenter(w / 2, h / 2));
  simulation.alpha(0.3).restart();
}});
</script>
</body>
</html>"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html_content, encoding="utf-8")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _safe_node_id(node: str) -> str:
    """Create a safe Mermaid/DOT node ID from a file path."""
    safe = node.replace("/", "_").replace(".", "_").replace("-", "_").replace("\\", "_")
    # Ensure it starts with a letter
    if safe and safe[0].isdigit():
        safe = "n" + safe
    return safe


def _escape_mermaid(text: str) -> str:
    """Escape text for safe embedding in Mermaid."""
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("<", "&lt;").replace(">", "&gt;")


def _escape_dot(text: str) -> str:
    """Escape text for safe embedding in DOT labels."""
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("<", "&lt;").replace(">", "&gt;")
