"""Visualization output generators for DepPulse dependency graphs.

Supports three output formats:
- Mermaid flowchart code
- Graphviz DOT format
- Interactive HTML dashboard with D3.js
"""

from __future__ import annotations

from pathlib import Path

import networkx as nx

from deppulse.models import GraphBuildResult, Language

# ---------------------------------------------------------------------------
# Mermaid
# ---------------------------------------------------------------------------


def render_mermaid_graph(
    graph: nx.DiGraph,
    *,
    title: str = "Dependency Graph",
    max_nodes: int = 200,
) -> str:
    """
    Render a dependency graph as a Mermaid flowchart.

    Groups nodes by language into subgraphs, colors edges by dependency kind,
    and marks high-risk nodes (high in-degree) with a warning style.
    """
    lines = ["flowchart LR", f'    %% {title} — generated by DepPulse']

    # Group nodes by language
    lang_groups: dict[str, list[str]] = {}
    node_lang: dict[str, Language] = {}
    node_risk: dict[str, bool] = {}

    for node in graph.nodes():
        data = graph.nodes.get(node, {})
        lang = data.get("language", Language.UNKNOWN)
        in_deg = graph.in_degree(node)
        high_risk = in_deg > 5  # heuristic: high fan-in = high risk

        node_lang[node] = lang
        node_risk[node] = high_risk

        suffix = data.get("suffix", Path(node).suffix)
        if suffix == ".py":
            lang_key = "Python"
        elif suffix == ".java":
            lang_key = "Java"
        elif suffix in (".kt", ".kts"):
            lang_key = "Kotlin"
        elif suffix in (".c", ".cpp", ".h", ".hpp", ".cc"):
            lang_key = "C/C++"
        else:
            lang_key = "Other"

        lang_groups.setdefault(lang_key, []).append(node)

    # Define subgraph IDs
    subgraph_ids: dict[str, str] = {}
    for i, key in enumerate(sorted(lang_groups.keys())):
        subgraph_ids[key] = f"sg{i}"

    # Declare subgraph styles
    color_map = {
        "Python": "#4B8BBE",
        "Java": "#B07219",
        "Kotlin": "#A18B00",
        "C/C++": "#F34B7D",
        "Other": "#AAAAAA",
    }

    shown = 0
    for lang_key, nodes in sorted(lang_groups.items()):
        sg_id = subgraph_ids[lang_key]
        _ = color_map.get(lang_key, "#AAAAAA")
        lines.append(f'    subgraph {sg_id} ["{lang_key}"]')
        for node in nodes[:max_nodes]:
            if shown >= max_nodes:
                break
            node_id = _safe_node_id(node)
            label = _escape_mermaid(Path(node).name)
            lines.append(f'        {node_id}["{label}"]')
            shown += 1
        lines.append("    end")

    # Add edge styles
    kind_colors = {
        "import": "#27ae60",
        "java_import": "#d35400",
        "kotlin_import": "#8e44ad",
        "include_local": "#2980b9",
        "include_system": "#7f8c8d",
    }

    # Draw edges
    for u, v, data in graph.edges(data=True):
        u_id = _safe_node_id(u)
        v_id = _safe_node_id(v)
        kind = data.get("kind", "unknown")
        _ = kind_colors.get(kind, "#95a5a6")
        lines.append(f"    {u_id} -.->|\"{kind}\"| {v_id}")

    if shown == 0:
        lines.append('    empty["(no nodes)"]')

    return "\n".join(lines)


def graph_to_mermaid(
    graph: nx.DiGraph,
    *,
    title: str = "Dependency Graph",
) -> str:
    """Alias for render_mermaid_graph for compatibility."""
    return render_mermaid_graph(graph, title=title)


# ---------------------------------------------------------------------------
# Graphviz DOT
# ---------------------------------------------------------------------------


def render_dot_graph(
    graph: nx.DiGraph,
    *,
    title: str = "Dependency Graph",
) -> str:
    """
    Render a dependency graph as Graphviz DOT format.

    Nodes are colored by language, sized by in-degree, and high-risk
    nodes (many dependents) are highlighted in red.
    """
    lines = [
        "digraph dependencies {",
        f'    label="{_escape_dot(title)}";',
        '    labelloc="t";',
        '    rankdir=LR;',
        '    node [shape=box, style="rounded,filled", fontname=Helvetica, width=0.3];',
        '    edge [arrowsize=0.5];',
    ]

    for node in graph.nodes():
        data = graph.nodes.get(node, {})
        suffix = data.get("suffix", Path(node).suffix)
        in_deg = graph.in_degree(node)
        high_risk = in_deg > 5

        if suffix == ".py":
            color = "#4B8BBE"
        elif suffix == ".java":
            color = "#B07219"
        elif suffix in (".kt", ".kts"):
            color = "#A18B00"
        elif suffix in (".c", ".cpp", ".h", ".hpp", ".cc"):
            color = "#F34B7D"
        else:
            color = "#AAAAAA"

        if high_risk:
            color = "#e74c3c"

        label = _escape_dot(Path(node).name)
        lines.append(f'    "{_escape_dot(node)}" [label="{label}", fillcolor="{color}", color="#fff"];')

    for u, v, data in graph.edges(data=True):
        kind = data.get("kind", "unknown")
        lines.append(f'    "{_escape_dot(u)}" -> "{_escape_dot(v)}" [label="{kind}", color="#95a5a6", fontsize=8];')

    lines.append("}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML Dashboard
# ---------------------------------------------------------------------------


def render_html_dashboard(
    result: GraphBuildResult,
    graph: nx.DiGraph,
    *,
    output_path: Path = Path("deppulse-dashboard.html"),
) -> None:
    """
    Generate a standalone interactive HTML dependency dashboard.

    Renders a "dependency constellation" — files as luminous nodes, dependencies
    as curved directional arcs. The visual language borrows from astronomical star
    charts: core files shine brightest, dependency flows trace orbital paths.
    """
    import json as _json

    # ---- Gather node / edge data ----------------------------------------
    nodes_data: list[dict] = []
    edges_data: list[dict] = []
    lang_map = {
        ".py": "python", ".java": "java", ".kt": "kotlin", ".kts": "kotlin",
        ".c": "cpp", ".cpp": "cpp", ".h": "cpp", ".hpp": "cpp",
        ".cc": "cpp", ".cxx": "cpp",
    }
    lang_colors = {
        "python": "#1e3a5f", "java": "#7a3a1a",
        "kotlin": "#6b4f14", "cpp": "#7a2038",
    }
    node_ids: dict[str, int] = {}
    deps_of: dict[str, list[str]] = {}
    rdeps_of: dict[str, list[str]] = {}

    for i, node in enumerate(graph.nodes()):
        attrs = graph.nodes.get(node, {})
        suffix = attrs.get("suffix", Path(node).suffix)
        lang = lang_map.get(suffix, "unknown")
        in_deg = graph.in_degree(node)
        out_deg = graph.out_degree(node)
        node_ids[node] = i
        nodes_data.append({
            "id": node,
            "name": Path(node).name,
            "lang": lang,
            "lang_color": lang_colors.get(lang, "#94a3b8"),
            "group": lang,
            "size": max(4.5, min(28, int(in_deg ** 0.65) + 5)),
            "in_deg": in_deg,
            "out_deg": out_deg,
            "dir": str(Path(node).parent),
            "bytes": attrs.get("size_bytes", 0),
            "symbols": attrs.get("symbol_count", 0),
        })

    for u, v, data in graph.edges(data=True):
        if u in node_ids and v in node_ids:
            src_lang = nodes_data[node_ids[u]]["lang"]
            edges_data.append({
                "source": u, "target": v,
                "kind": str(data.get("kind", "unknown")),
                "line": data.get("line_number", 0),
                "color": lang_colors.get(src_lang, "#94a3b8"),
            })
            deps_of.setdefault(u, []).append(v)
            rdeps_of.setdefault(v, []).append(u)

    for nd in nodes_data:
        nid = nd["id"]
        nd["deps"] = deps_of.get(nid, [])
        nd["rdeps"] = rdeps_of.get(nid, [])

    stats = result.stats
    stats_data = {
        "total_files": stats.total_files,
        "total_edges": stats.total_edges,
        "files_with_cycles": stats.files_with_cycles,
    }

    # ---- HTML template (loaded from file to keep visualize.py clean) -----
    _t = (Path(__file__).parent / "dashboard_template.html").read_text(encoding="utf-8")

    # ---- Inject data & write ---------------------------------------------
    html = _t.replace("__NODES__", _json.dumps(nodes_data, ensure_ascii=False))
    html = html.replace("__EDGES__", _json.dumps(edges_data, ensure_ascii=False))
    html = html.replace("__STATS__", _json.dumps(stats_data, ensure_ascii=False))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html, encoding="utf-8")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _safe_node_id(node: str) -> str:
    """Create a safe Mermaid/DOT node ID from a file path."""
    safe = node.replace("/", "_").replace(".", "_").replace("-", "_").replace("\\", "_")
    # Ensure it starts with a letter
    if safe and safe[0].isdigit():
        safe = "n" + safe
    return safe


def _escape_mermaid(text: str) -> str:
    """Escape text for safe embedding in Mermaid."""
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("<", "&lt;").replace(">", "&gt;")


def _escape_dot(text: str) -> str:
    """Escape text for safe embedding in DOT labels."""
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("<", "&lt;").replace(">", "&gt;")
